apiVersion: v1
kind: Service
metadata:
  labels:
    app: mittag-app-service
  name: mittag-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: mittag-app
